DELETE FROM facilities
WHERE
    facsubgrp = 'Shelters and Transitional Housing'
    OR factype = 'Family Foster Care'
    OR factype = 'Residential Care'
    OR factype = 'Residential Care Services '
    OR factype = 'Specialized FFC: Children Who Have Been Sexually Exploited'
    OR factype = 'Specialized FFC: Children With Special Medical Needs, Including HIV and/or AIDS'
    OR factype = 'Specialized FFC: Children with Mental Retardation, Developmental Delays, and/or Developmental Disabilities'
    OR factype = 'Specialized FFC: Rapid Intervention Teams'
    OR factype = 'Specialized FFC: Treatment FFC for Children With Moderate to Severe Emotional and/or Behavioral Disorders'
    OR factype = 'Specialized NSP: Youth with Fire Setting Behaviors'
    OR factype = 'Specialized NSP: Youth with MR/DD'
    OR factype = 'Specialized PC: Families with Children Who Have Been Sexually Exploited'
    OR factype = 'Specialized PC: Families with Children or Parents Who Are Deaf/Hearing Impaired'
    OR factype = 'Specialized PC: Family Treatment/Rehabilitation'
    OR factype = 'Specialized PC: Family Treatment/Rehabilitation'
    OR factype = 'Specialized PC: Special Medical and Developmental Preventive Program'
    OR factype = 'Court Based Programs'
    OR factype = 'Court Based Programs'
    OR factype = 'Crime Victim Advocate Program'
    OR factype = 'Crime Victims Services'
    OR factype = 'AIDS: Counseling, Meals, and Other Services'
    OR factype = 'AIDS: Non-Emergency Congregate Housing'
    OR factype = 'AIDS: Permanent Congregate Housing'
    OR factype = 'HIV/AIDS Services Administration'
    OR factype = 'HIV/AIDS Services Administration'
    OR factype = 'Limited-Secure Placement'
    OR factype LIKE '%Non-Secure%'
    OR factype LIKE '%Non-secure%'
    OR factype LIKE '%NSP%'
    OR facname LIKE '%Non-secure%'
    OR facname LIKE '%Non-Secure%'
    OR facname LIKE '%NSP%'
    OR facname LIKE '%NSD%'
    OR facname LIKE '%Nsd%'
    OR facname LIKE '%Nsp%';
