facdb = [
    "facdb_datasources",
    "facdb_uid_key",
    "dcp_facilities_togeocode",

    # DCP Data Sources
    "dcp_mappluto",
    "dcp_boroboundaries_wi",
    "dcp_cdboundaries",
    "dcp_censustracts",
    "dcp_councildistricts",
    "dcp_ntaboundaries",
    "doitt_zipcodes",

    # Outside Datasets
    "bic_facilities_tradewaste",
    "dca_facilities_operatingbusinesses",
    "dcla_facilities_culturalinstitutions",
    "dcp_facilities_sfpsd",
    "dcp_facilities_pops",
    "dfta_facilities_contracts",
    "doe_facilities_busroutesgarages",
    "doe_facilities_universalprek",
    "dohmh_facilities_daycare",
    "dpr_parksproperties",
    "hhc_facilities_hospitals",
    "nycha_facilities_policeservice",
    "nysdec_facilities_lands",
    "nysdec_facilities_solidwaste",
    "nysdoh_facilities_healthfacilities",
    "nysdoh_nursinghomebedcensus",
    "nysomh_facilities_mentalhealth",
    "nysopwdd_facilities_providers",
    "nysparks_facilities_historicplaces",
    "nysparks_facilities_parks",
    "usdot_facilities_airports",
    "usdot_facilities_ports",
    "usnps_facilities_parks",

    # ---
    "acs_facilities_daycareheadstart",
    "dcas_facilities_colp",
    "dhs_facilities_shelters",
    "doe_facilities_schoolsbluebook",
    "dot_facilities_pedplazas",
    "dot_facilities_parkingfacilities",
    "dot_facilities_bridgehouses",
    "dot_facilities_ferryterminalslandings",
    "dot_facilities_mannedfacilities",
    "dsny_facilities_mtsgaragemaintenance",
    "foodbankny_facilities_foodbanks",
    "hhs_facilities_fmscontracts",
    "hhs_facilities_financialscontracts",
    "hhs_facilities_proposals",
    "nysoasas_facilities_programs", ## Being shared with us monthly by email in xlsx
    "nysed_facilities_activeinstitutions", ## Actually is open but need to figue out url
    "nysed_nonpublicenrollment", ## Actually is open but in xlsx that needs to be formatted
    "omb_facilities_libraryvisits",
    "dycd_facilities_compass",
    "dycd_facilities_otherprograms",
    "hra_facilities_centers",
    "sbs_facilities_workforce1",
]
